fix the subject lines in investigations
certat/intelmq pull request #118
Opened 2017-03-03 13:37 UTC by aaronkaplan

as requested by @otmarlendl

2017-03-06 09:48 UTC, ghost requested changes

2017-03-06 09:48 UTC, wagner-certat commented on intelmq/lib/intelmqcli.py
> +    "misp.event_uuid",
This already exists - in your branch and in in master. Two lines above.

2017-03-20 11:13 UTC, ghost approved these changes

2017-06-26 09:51 UTC, aaronkaplan reviewed
okay, seems to be the case already in -prod anyway

2017-06-26 09:53 UTC, aaronkaplan commented
note necessary anymore

2017-06-26 09:53 UTC, closed without merging